import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('preferredLanguage') || 'en');

    // Ensure default is English if not set
    useEffect(() => {
        if (!localStorage.getItem('preferredLanguage')) {
            localStorage.setItem('preferredLanguage', 'en');
        }
    }, []);

    const translations = {
        en: {
            title: 'English',
            chat: 'Chat',
            myAgents: 'My Agents',
            marketplace: 'Marketplace',
            settings: 'Settings',
            adminDashboard: 'Admin Dashboard',
            notifications: 'Notifications',
            personalProfile: 'Profile',
            helpFaq: 'Help & FAQ',
            signOut: 'LOG OUT',
            language: 'Language',
            mode: 'Appearance',
            light: 'Light',
            dark: 'Dark',
            activeConnection: 'Connected',
            typeMessage: 'Type your message...',
            privateSupport: 'Support',
            secureProtocol: 'SECURE',
            history: 'History',
            newInstance: 'New Instance',
            memoryEmpty: 'No History',
            initializeLogic: 'START CHAT',
            chatGreeting: 'Hello! Your AI agent is ready. How can I help you today?',
            askPlaceholder: 'Ask anything...',
            my: 'My',
            agentsHeading: 'Agents',
            manageAgentsDesc: 'Manage your collection of AI agents.',
            docs: 'Docs',
            use: 'USE',
            info: 'Info',
            marketplaceHeading: 'AI MALL MARKETPLACE',
            marketplaceSubheading: 'DISCOVER INTELLIGENT AGENTS',
            aiAgents: 'AGENTS',
            searchPlaceholder: 'Search agents...',
            viewInfo: 'VIEW INFO',
            notificationsHeading: 'Notifications',
            notificationsDesc: 'Stay updated with your latest alerts.',
            markAsRead: 'MARK AS READ',
            delete: 'DELETE',
            noNotificationsTitle: 'No Notifications',
            noNotificationsDesc: 'You have no new notifications at this time.',
            onlineReady: 'Online',
            processingReality: 'Processing...',
            synced: 'SYNCED',
            untitledSession: 'New Session',
            cancel: 'CANCEL',
            subscribeNow: 'SUBSCRIBE NOW',
            chatHistory: 'CHAT HISTORY',
            catAll: 'ALL',
            catBusiness: 'BUSINESS',
            catData: 'DATA & INTELLIGENCE',
            catSales: 'SALES & MARKETING',
            catHr: 'HR & FINANCE',
            catDesign: 'DESIGN & CREATIVE',
            catMedical: 'MEDICAL',
            knowledge: 'KNOWLEDGE',
            support: 'SUPPORT',
            generalGuidelines: 'GENERAL GUIDELINES',
            issueCategory: 'CATEGORY',
            caseDetails: 'DETAILS',
            specifyRequest: 'Describe your request...',
            sendMessage: 'SEND MESSAGE',
            sending: 'SENDING...',
            ticketCreated: 'TICKET CREATED!',
            dismiss: 'DISMISS',
            directChannel: 'Support Channel',
            generalInquiry: 'General Inquiry',
            paymentIssue: 'Payment Issue',
            refundRequest: 'Refund Request',
            technicalSupport: 'Technical Support',
            accountAccess: 'Account Access',
            other: 'Other',
            criticalAlert: 'ALERT',
            systemMaintenance: 'MAINTENANCE',
            killSwitchMsg: 'System is temporarily offline. All services are suspended.',
            maintenanceMsg: 'The system is currently in maintenance mode.',
            faq1_q: "What is AI-Mall?",
            faq1_a: "It is a marketplace for specialized AI agents built for specific tasks like coding, writing, or analysis.",
            faq2_q: "How does the subscription work?",
            faq2_a: "We offer a flexible subscription model per agent. You can choose a plan that fits your business needs.",
            faq3_q: "Which AI models are used?",
            faq3_a: "We use advanced AI models to ensure high speed and reasoning capabilities.",
            faq4_q: "Is my data secure?",
            faq4_a: "Yes, we use isolated environments and strict protocols to ensure your information is safe.",
            faq5_q: "How many agents can I use?",
            faq5_a: "You can use any agent available in the marketplace. We are constantly adding new ones.",
            faq6_q: "Can I create my own agent?",
            faq6_a: "Custom agent creation is coming soon in the next phase.",
            faq7_q: "Why choose AI-Mall?",
            faq7_a: "AI-Mall offers ready-to-use agents tuned for specific jobs, so you don't need to learn prompting.",
            faq8_q: "Is it mobile-friendly?",
            faq8_a: "Yes, the interface works smoothly on phones and tablets.",
            faq9_q: "How do I get started?",
            faq9_a: "Try the demo now or contact us for a walkthrough.",
            syncingData: 'Loading data...',
            secDataPrivacy: "Privacy Policy",
            secAcceptableConduct: "Terms of Use",
            secDisclaimer: "AI Disclaimer",
            secHeading: "Privacy & Security",
            secSubheading: "Our policies on data protection and system security.",
            secSupportNode: "Support",
            secSupportDesc: "Need help? Our support team is here to assist you.",
            secIncidentReport: "Report a Problem",
            secIncidentDesc: "Found a bug? Let us know so we can fix it.",
            secOpenDiagnosis: "Contact Support",
            secDataCollection: "1.1 Data Collection",
            secDataSharing: "1.2 Data Sharing",
            servicesRestored: 'SERVICES RESTORED',
            subExpiringSoon: 'Subscription Expiring Soon',
            newSupportReply: 'New Support Reply',
            killSwitchDeactivatedMsg: 'Global Kill-Switch Deactivated. All AI services are now active.',
            subExpiringMsg: "Reminder: Your subscription for '{agentName}' expires in less than 2 days.",
            supportReplyMsg: "A new reply has been added to your ticket: {subject}",
            systemRestored: 'SYSTEM RESTORED',
            maintenanceCompleteMsg: 'Maintenance is complete. System is fully operational.',
            moreIn: 'MORE IN {category}',
            noOtherApps: 'No other apps in this category yet.',
            'fireflies.ai': 'fireflies.ai',
            'AI meeting assistant that automatically records, transcribes, and summarizes conversations from calls and meetings, making collaboration and note-taking effortless for teams.': 'AI meeting assistant that automatically records, transcribes, and summarizes conversations from calls and meetings, making collaboration and note-taking effortless for teams.',
            'ElevenLabs': 'ElevenLabs',
            'ElevenLabs provides creators, developers, and enterprises with state-of-the-art AI audio technology for generating and customizing speech and sound across various applications.': 'ElevenLabs provides creators, developers, and enterprises with state-of-the-art AI audio technology for generating and customizing speech and sound across various applications.',
            'AIBOT': 'AIBOT',
            'AICRAFT': 'AICRAFT',
            controlCenter: 'Dashboard',
            appRegistry: 'Apps',
            neuralSupport: 'Support',
            userIdentities: 'Users',
            vendorNodes: 'Vendors',
            nexusApprovals: 'Approvals',
            accessSecurity: 'Access Control',
            coreProtocol: 'Settings',
            fleetOps: 'Operations',
            nexusMeta: 'App Data',
            deactivateToken: 'Deactivate',
            protocolStream: 'Activity Log',
            status: 'Status',
            nominal: 'Active',
            systemOverlord: 'Admin',
            superUser: 'Super Admin',
            userManagement: 'User Management',
            manageUsersDesc: 'Manage platform users and view subscriptions',
            searchUsers: 'Search users...',
            user: 'User',
            role: 'Role',
            subscribedAgents: 'Subscribed Agents',
            totalSpent: 'Total Spent',
            actions: 'Actions',
            admin: 'Admin',
            userRole: 'User',
            active: 'Active',
            pending: 'Pending',
            blocked: 'Blocked',
            myApps: 'My Apps',
            yourApps: 'Registered Apps',
            newApp: 'Create App',
            appName: 'App Name',
            pricing: 'Price',
            quickActions: 'Actions',
            success: 'Success',
            appCreatedSuccess: 'App "{name}" has been created.',
            approvals: 'Approvals',
            verification: 'Review',
            identityIntegrityAudit: 'Audit Log',
            pendingCases: 'Pending',
            source: 'Source',
            externalVendor: 'External Vendor',
            authorize: 'Approve',
            queueDepleted: 'No Pending Tasks',
            noPendingVerifications: 'Everything is up to date.',
            finalApproval: 'Approve Agent',
            authorizeAgentDesc: 'Are you sure you want to approve this agent for the marketplace?',
            regress: 'Back',
            verifyCase: 'Confirm Approval',
            'business os': 'Business',
            'data & intelligence': 'Data',
            'sales & marketing': 'Marketing',
            'hr & finance': 'Finance',
            'design & creative': 'Design',
            'medical & health ai': 'Medical',
            userSupport: 'Support Tickets',
            manageInquiriesDesc: 'Manage user support tickets',
            searchTickets: 'Search...',
            messagePreview: 'Message',
            date: 'Date',
            userSupportType: 'User Support',
            open: 'Open',
            noActiveTickets: 'No Active Tickets',
            accessPermissionsUpdateRequired: 'Update Required',
            accessPermissionsUpdateMsg: 'Session expired. Please log in again.',
            updateSession: 'Log Out',
            vendorSupport: 'Vendor Support',
            manageVendorInquiries: 'Manage vendor support tickets',
            all: 'All',
            ticketId: 'Ticket ID',
            description: 'Description',
            reply: 'Reply',
            resolve: 'Resolve',
            noVendorTickets: 'No tickets found.',
            strategicOversight: 'Overview',
            control: 'Admin',
            center: 'Panel',
            deepTelemetry: 'System statistics and financial reports.',
            searchProtocols: 'SEARCH...',
            ecosystem: 'System',
            vitals: 'Stats',
            activeUnits: 'Active Agents',
            revenueFlow: 'Revenue',
            rootMaster: 'Admin User',
            unifiedSecurity: 'Full Access',
            globalBalance: 'System Balance',
            provisionAgent: 'Add Agent',
            vendorMatrix: 'Vendors',
            auditAll: 'Check All',
            transactions: 'Sales',
            systemHealth: 'System Health',
            neuralLatency: 'Latency',
            uptimeProtocol: 'Uptime',
            packetIntegrity: 'Data Integrity',
            statusSynchronized: 'ACTIVE',
            statusStable: 'STABLE',
            statusValidated: 'VALIDATED'
        },
        ar: {
            title: 'العربية (Arabic)',
            chat: 'محادثة',
            myAgents: 'وكلائي',
            marketplace: 'المتجر',
            settings: 'الإعدادات',
            adminDashboard: 'لوحة التحكم',
            notifications: 'الإشعارات',
            personalProfile: 'الملف الشخصي',
            helpFaq: 'المساعدة والأسئلة الشائعة',
            signOut: 'تسجيل الخروج',
            language: 'اللغة',
            mode: 'الوضع',
            light: 'فاتح',
            dark: 'داكن',
            activeConnection: 'اتصال نشط',
            typeMessage: 'اكتب رسالتك الآمنة...',
            privateSupport: 'دعم خاص',
            secureProtocol: 'بروتوكول آمن نشط',
            history: 'السجل',
            newInstance: 'مثيل جديد',
            memoryEmpty: 'الذاكرة فارغة',
            initializeLogic: 'تهيئة المنطق',
            chatGreeting: 'وكيل الذكاء الاصطناعي المتقدم الخاص بك جاهز للتفاعل. كيف يمكننا تحسين سير عملك اليوم؟',
            askPlaceholder: 'اسأل عيسى...',
            my: 'وكلائي',
            agentsHeading: 'وكلاء',
            manageAgentsDesc: 'إدارة مجموعة وكلاء الذكاء الاصطناعي الخاصة بك.',
            docs: 'الوثائق',
            use: 'استخدام',
            info: 'معلومات',
            marketplaceHeading: 'AI MALL MARKETPLACE',
            marketplaceSubheading: 'اكتشف الوكلاء الأذكياء',
            aiAgents: 'وكلاء الذكاء الاصطناعي',
            searchPlaceholder: 'البحث عن وكلاء...',
            viewInfo: 'عرض المعلومات',
            notificationsHeading: 'الإشعارات',
            notificationsDesc: 'ابق على اطلاع بآخر التنبيهات.',
            markAsRead: 'تحديد كقروء',
            delete: 'حذف',
            noNotificationsTitle: 'تسلسل فارغ',
            noNotificationsDesc: 'لم يتم اكتشاف أي إرسالات عصبية. نظامك البيئي يصل حاليًا إلى ذروة الاستقرار.',
            onlineReady: 'متصل وجاهز',
            processingReality: 'معالجة الواقع',
            synced: 'متزامن',
            untitledSession: 'جلسة بدون عنوان',
            cancel: 'إلغاء',
            subscribeNow: 'اشترك الآن',
            chatHistory: 'سجل المحادثة',
            catAll: 'الكل',
            catBusiness: 'نظام تشغيل الأعمال',
            catData: 'البيانات والذكاء',
            catSales: 'المبيعات والتسويق',
            catHr: 'الموارد البشرية والمالية',
            catDesign: 'التصميم والإبداع',
            catMedical: 'الصحة والذكاء الاصطناعي الطبي',
            knowledge: 'المعرفة',
            support: 'الدعم',
            generalGuidelines: 'إرشادات عامة',
            issueCategory: 'فئة المشكلة',
            caseDetails: 'تفاصيل الحالة',
            specifyRequest: 'حدد طلبك...',
            sendMessage: 'إرسال الرسالة',
            sending: 'جارٍ الإرسال...',
            ticketCreated: 'تم إنشاء التذكرة!',
            dismiss: 'إلغاء',
            directChannel: 'القناة المباشرة',
            generalInquiry: 'استفسار عام',
            paymentIssue: 'مشكلة الدفع',
            refundRequest: 'طلب استرداد الأموال',
            technicalSupport: 'الدعم الفني',
            accountAccess: 'الدخول للحساب',
            other: 'أخرى',
            criticalAlert: 'تنبيه حرج',
            systemMaintenance: 'صيانة النظام',
            killSwitchMsg: 'تم تفعيل مفتاح الإيقاف العالمي. تم تعليق جميع خدمات الذكاء الاصطناعي مؤقتًا.',
            maintenanceMsg: 'النظام حاليًا في وضع الصيانة.',
            faq1_q: "ما هو AI-Mall بالضبط؟",
            faq1_a: "إنه سوق لوكلاء الذكاء الاصطناعي المتخصصين. على عكس روبوتات الدردشة العامة، تختار 'موظفين' محددين (وكلاء) لمهام محددة مثل البرمجة، الكتابة، أو التحليل.",
            faq2_q: "كيف تعمل خطة الاشتراك؟",
            faq2_a: "نقدم نموذج اشتراك مرنًا لكل وكيل. يمكنك اختيار الخطة التي تناسب احتياجات عملك، مع خيارات للتوسع مع نموك.",
            faq3_q: "ما هي نماذج الذكاء الاصطناعي التي تشغل هؤلاء الوكلاء؟",
            faq3_a: "نستخدم نماذج ذكاء اصطناعي متقدمة لضمان سرعة عالية وقدرات تفكير فائقة.",
            faq4_q: "هل بياناتي آمنة على الخادم؟",
            faq4_a: "نعم، خوادمنا مصممة بمعايير المؤسسات. نستخدم بيئات معزولة لكل جلسة ونلتزم بصرامة ببروتوكولات خصوصية البيانات لضمان أمان معلوماتك.",
            faq5_q: "كم عدد الوكلاء الذين يمكنني استخدامهم الآن؟",
            faq5_a: "نعرض حاليًا أفضل وكيلين لدينا، AIBOT و AICRAFT، اللذين يغطيان أوسع نطاق من حالات الاستخدام التجاري.",
            faq6_q: "هل يمكنني إنشاء وكيلي الخاص؟",
            faq6_a: "حاليًا، يضم السوق وكلاءنا المختارين والمتحقق منهم. إنشاء الوكلاء المخصصين موجود في خارطة الطريق للمرحلة القادمة.",
            faq7_q: "لماذا يجب أن أستخدم هذا بدلاً من حلول الذكاء الاصطناعي الأخرى؟",
            faq7_a: "يوفر AI-Mall تجربة منسقة مع تدفقات متخصصة. لا تحتاج إلى هندسة الأوامر؛ فدراتنا مضبوطة بالفعل لوظائفها المحددة.",
            faq8_q: "هل هو متوافق مع الأجهزة المحمولة؟",
            faq8_a: "نعم، الواجهة سريعة الاستجابة تمامًا وتعمل بسلاسة على هاتفك أو جهازك اللوحي.",
            faq9_q: "كيف أبدأ؟",
            faq9_a: "يمكنك تجربة العرض التوضيحي الآن أو حجز جولة مخصصة مع فريقنا لمعرفة كيف يناسب سير عملك المحدد.",
            syncingData: 'جاري مزامنة بيانات نيكسوس...',
            secDataPrivacy: "خصوصية البيانات والحماية",
            secAcceptableConduct: "السلوك العصبي المقبول",
            secDisclaimer: "إخلاء مسؤولية استجابة الذكاء الاصطناعي",
            secHeading: "الأمن والإرشادات.",
            secSubheading: "تأسيس إطار للاستخدام القانوني وحماية البيانات والأمن التشغيلي داخل الغلاف الحيوي لـ AI-Mall™.",
            secSupportNode: "عقدة الدعم",
            secSupportDesc: "هل تواجه شذوذًا أو تحتاج إلى تدخل يدوي؟ مصفوفة الدعم العصبي لدينا مستعدة.",
            secIncidentReport: "تقرير الحادث",
            secIncidentDesc: "أبلغ عن المشاكل البصرية أو أخطاء المنطق أو الخروقات لفريق الهندسة لدينا.",
            secOpenDiagnosis: "فتح نموذج التشخيص",
            secDataCollection: "1.1 جمع البيانات",
            secDataSharing: "1.2 مشاركة البيانات",
            servicesRestored: 'تم استعادة الخدمات',
            subExpiringSoon: 'قرب انتهاء الاشتراك',
            newSupportReply: 'رد دعم جديد',
            killSwitchDeactivatedMsg: 'تم إلغاء تفعيل مفتاح الإيقاف العالمي. جميع خدمات الذكاء الاصطناعي نشطة الآن.',
            subExpiringMsg: "تذكير: اشتراكك في '{agentName}' ينتهي خلال أقل من يومين.",
            supportReplyMsg: "تمت إضافة رد جديد على تذكرتك: {subject}",
            systemRestored: 'تم استعادة النظام',
            maintenanceCompleteMsg: 'اكتملت الصيانة. النظام يعمل بشكل كامل.',
            moreIn: 'المزيد في {category}',
            noOtherApps: 'لا توجد تطبيقات أخرى في هذه الفئة حتى الآن.',
            'fireflies.ai': 'fireflies.ai',
            'AI meeting assistant that automatically records, transcribes, and summarizes conversations from calls and meetings, making collaboration and note-taking effortless for teams.': 'مساعد اجتماعات بالذكاء الاصطناعي يقوم تلقائيًا بتسجيل النصوص وتلخيص المحادثات من المكالمات والاجتماعات، مما يجعل التعاون وتدوين الملاحظات سهلاً للفرق.',
            'ElevenLabs': 'ElevenLabs',
            'ElevenLabs provides creators, developers, and enterprises with state-of-the-art AI audio technology for generating and customizing speech and sound across various applications.': 'توفر ElevenLabs للمبدعين والمطورين والمؤسسات تقنية صوتية متقدمة بالذكاء الاصطناعي لإنشاء وتخصيص الكلام والصوت عبر تطبيقات مختلفة.',
            'AIBOT': 'أي بوت',
            'AICRAFT': 'أي كرافت'
        },
        hi: {
            title: 'हिन्दी (Hindi)',
            chat: 'चैट',
            myAgents: 'मेरे एजेंट',
            marketplace: 'बाज़ार',
            settings: 'सेटिंग्स',
            adminDashboard: 'एडमिन डैशबोर्ड',
            notifications: 'सूचनाएं',
            personalProfile: 'व्यक्तिगत प्रोफ़ाइल',
            helpFaq: 'सहायता और अक्सर पूछे जाने वाले प्रश्न',
            signOut: 'लोग आउट',
            language: 'भाषा',
            mode: 'मोड',
            light: 'लाइट',
            dark: 'डार्क',
            activeConnection: 'सक्रिय कनेक्शन',
            typeMessage: 'अपना सुरक्षित संदेश टाइप करें...',
            privateSupport: 'निजी सहायता',
            secureProtocol: 'सुरक्षित प्रोटोकॉल सक्रिय',
            history: 'इतिहास',
            newInstance: 'नया इंस्टेंस',
            memoryEmpty: 'मेमोरी खाली है',
            initializeLogic: 'लॉजिक प्रारंभ करें',
            chatGreeting: 'आपका उन्नत एआई एजेंट बातचीत के लिए तैयार है। आज हम आपके वर्कफ़्लो को कैसे अनुकूलित कर सकते हैं?',
            askPlaceholder: 'आइसा से पूछें...',
            my: 'मेरे',
            agentsHeading: 'एजेंट',
            manageAgentsDesc: 'अपने एआई एजेंटों के संग्रह का प्रबंधन करें।',
            docs: 'दस्तावेज़',
            use: 'उपयोग करें',
            info: 'जानकारी',
            marketplaceHeading: 'AI MALL MARKETPLACE',
            marketplaceSubheading: 'बुद्धिमान एजेंटों की खोज करें',
            aiAgents: 'एआई एजेंट',
            searchPlaceholder: 'एजेंट खोजें...',
            viewInfo: 'जानकारी देखें',
            notificationsHeading: 'सूचनाएं',
            notificationsDesc: 'अपने नवीनतम अलर्ट के साथ अपडेट रहें।',
            markAsRead: 'पढ़ा हुआ मानें',
            delete: 'हटाएं',
            noNotificationsTitle: 'शून्य अनुक्रम',
            noNotificationsDesc: 'कोई सूचना नहीं मिली। आपका सिस्टम वर्तमान में पूर्ण स्थिरता पर है।',
            onlineReady: 'ऑनलाइन और तैयार',
            processingReality: 'प्रक्रिया चल रही है',
            synced: 'सिंक किया गया',
            untitledSession: 'बिना शीर्षक वाला सत्र',
            cancel: 'रद्द करें',
            subscribeNow: 'अभी सब्सक्राइब करें',
            chatHistory: 'चैट इतिहास',
            catAll: 'सभी',
            catBusiness: 'बिजनेस ओएस',
            catData: 'डेटा और खुफिया',
            catSales: 'बिक्री और विपणन',
            catHr: 'एचआर और वित्त',
            catDesign: 'डिजाइन और रचनात्मक',
            catMedical: 'चिकित्सा और स्वास्थ्य एआई',
            knowledge: 'ज्ञान',
            support: 'सहयोग',
            generalGuidelines: 'सामान्य दिशा - निर्देश',
            issueCategory: 'समस्या श्रेणी',
            caseDetails: 'मामले का विवरण',
            specifyRequest: 'अपना अनुरोध निर्दिष्ट करें...',
            sendMessage: 'संदेश भेजें',
            sending: 'भेजा जा रहा है...',
            ticketCreated: 'टिकट बनाया गया!',
            dismiss: 'खारिज करें',
            directChannel: 'सीधा चैनल',
            generalInquiry: 'सामान्य पूछताछ',
            paymentIssue: 'भुगतान संबंधी समस्या',
            refundRequest: 'धनवापसी अनुरोध',
            technicalSupport: 'तकनीकी सहायता',
            accountAccess: 'खाता पहुंच',
            other: 'अन्य',
            criticalAlert: 'महत्वपूर्ण चेतावनी',
            systemMaintenance: 'सिस्टम रखरखाव',
            killSwitchMsg: 'ग्लोबल किल-स्विच सक्रिय। सभी एआई सेवाएं क्षणिक रूप से निलंबित हैं।',
            maintenanceMsg: 'सिस्टम अभी रखरखाव मोड में है।',
            faq1_q: "एआई-मॉल वास्तव में क्या है?",
            faq1_a: "यह विशेष एआई एजेंटों के लिए एक बाज़ार है। एक सामान्य चैटबॉट के विपरीत, आप कोडिंग, लेखन या विश्लेषण जैसे विशिष्ट कार्यों के लिए विशिष्ट 'कर्मचारियों' (एजेंटों) को चुनते हैं।",
            faq2_q: "सदस्यता योजना कैसे काम करती है?",
            faq2_a: "हम प्रति एजेंट एक लचीला सदस्यता मॉडल प्रदान करते हैं। आप एक ऐसी योजना चुन सकते हैं जो आपकी व्यावसायिक आवश्यकताओं के अनुकूल हो, जिसमें आपके विकास के साथ विस्तार करने के विकल्प हों।",
            faq3_q: "कौन से एआई मॉडल इन एजेंटों को शक्ति प्रदान करते हैं?",
            faq3_a: "हम उच्च गति और तर्क क्षमताओं को सुनिश्चित करने के लिए उन्नत एआई मॉडल का उपयोग करते हैं।",
            faq4_q: "क्या मेरा डेटा सर्वर पर सुरक्षित है?",
            faq4_a: "हाँ, हमारे सर्वर एंटरप्राइज़-ग्रेड हैं। हम प्रत्येक सत्र के लिए अलग वातावरण का उपयोग करते हैं और आपकी जानकारी सुरक्षित रखने के लिए डेटा गोपनीयता प्रोटोकॉल का सख्ती से पालन करते हैं।",
            faq5_q: "मैं अभी कितने एजेंटों का उपयोग कर सकता हूँ?",
            faq5_a: "हम वर्तमान में अपने शीर्ष 2 एजेंटों, AIBOT और AICRAFT को प्रदर्शित कर रहे हैं, जो व्यावसायिक उपयोग के मामलों की सबसे विस्तृत श्रृंखला को कवर करते हैं।",
            faq6_q: "क्या मैं अपना खुद का एजेंट बना सकता हूँ?",
            faq6_a: "वर्तमान में, बाज़ार में हमारे क्यूरेटेड, सत्यापित एजेंट हैं। कस्टम एजेंट निर्माण अगले चरण के लिए हमारे रोडमैप पर है।",
            faq7_q: "मुझे अन्य एआई समाधानों के बजाय इसका उपयोग क्यों करना चाहिए?",
            faq7_a: "एआई-मॉल विशेष प्रवाह के साथ एक क्यूरेटेड अनुभव प्रदान करता है। आपको प्रॉम्प्ट-इंजीनियर की आवश्यकता नहीं है; हमारे एजेंट पहले से ही अपनी विशिष्ट नौकरियों के लिए ट्यून किए गए हैं।",
            faq8_q: "क्या यह मोबाइल के अनुकूल है?",
            faq8_a: "हां, इंटरफ़ेस पूरी तरह से उत्तरदायी है और आपके फोन या टैबलेट पर आसानी से काम करता है।",
            faq9_q: "मैं शुरुआत कैसे करूँ?",
            faq9_a: "आप अभी डेमो आज़मा सकते हैं या यह देखने के लिए हमारी टीम के साथ एक व्यक्तिगत पूर्वाभ्यास बुक कर सकते हैं कि यह आपके विशिष्ट वर्कफ़्लो में कैसे फिट बैठता है।",
            syncingData: 'नेक्सस डेटा सिंक हो रहा है...',
            secDataPrivacy: "डेटा गोपनीयता और सुरक्षा",
            secAcceptableConduct: "स्वीकार्य तंत्रिका आचरण",
            secDisclaimer: "एआई प्रतिक्रिया अस्वीकरण",
            secHeading: "सुरक्षा और दिशानिर्देश.",
            secSubheading: "एआई-मॉल™ बायोस्फीयर के भीतर कानूनी उपयोग, डेटा संरक्षण और परिचालन सुरक्षा के लिए ढांचा स्थापित करना।",
            secSupportNode: "सहायता नोड",
            secSupportDesc: "क्या आप विसंगतियों का सामना कर रहे हैं या मैनुअल हस्तक्षेप की आवश्यकता है? हमारी तंत्रिका सहायता सरणी तैयार है।",
            secIncidentReport: "घटना रिपोर्ट",
            secIncidentDesc: "हमारे इंजीनियरिंग टीम को दृश्य कलाकृतियों, तर्क त्रुटियों या सुरक्षा उल्लंघनों की रिपोर्ट करें।",
            secOpenDiagnosis: "निदान फॉर्म खोलें",
            secDataCollection: "1.1 डेटा संग्रह",
            secDataSharing: "1.2 डेटा साझाकरण",
            servicesRestored: 'सेवाएं बहाल',
            subExpiringSoon: 'सदस्यता जल्द समाप्त हो रही है',
            newSupportReply: 'नया सहायता उत्तर',
            killSwitchDeactivatedMsg: 'ग्लोबल किल-स्विच डीएक्टिवेट हो गया। सभी एआई सेवाएं अब सक्रिय हैं।',
            subExpiringMsg: "अनुस्मारक: '{agentName}' के लिए आपकी सदस्यता 2 दिनों से कम समय में समाप्त हो जाएगी।",
            supportReplyMsg: "आपकी टिकट पर एक नया उत्तर जोड़ा गया है: {subject}",
            systemRestored: 'सिस्टम बहाल',
            maintenanceCompleteMsg: 'रखरखाव पूरा हो गया है। सिस्टम पूरी तरह से चालू है।',
            moreIn: '{category} में और देखें',
            noOtherApps: 'इस श्रेणी में अभी कोई अन्य ऐप नहीं है।',
            'fireflies.ai': 'fireflies.ai',
            'AI meeting assistant that automatically records, transcribes, and summarizes conversations from calls and meetings, making collaboration and note-taking effortless for teams.': 'एआई मीटिंग सहायक जो कॉल और मीटिंग से बातचीत को स्वचालित रूप से रिकॉर्ड, ट्रांसक्राइब और सारांशित करता है, जिससे टीमों के लिए सहयोग और नोट लेना आसान हो जाता है।',
            'ElevenLabs': 'ElevenLabs',
            'ElevenLabs provides creators, developers, and enterprises with state-of-the-art AI audio technology for generating and customizing speech and sound across various applications.': 'ElevenLabs रचनाकारों, डेवलपर्स और उद्यमों को विभिन्न अनुप्रयोगों में भाषण और ध्वनि उत्पन्न करने और अनुकूलित करने के लिए अत्याधुनिक एआई ऑडियो तकनीक प्रदान करता है।',
            'AIBOT': 'एआई बॉट',
            'AICRAFT': 'एआई क्राफ्ट',
            controlCenter: 'कंट्रोल सेंटर',
            appRegistry: 'ऐप रजिस्ट्री',
            neuralSupport: 'न्यूरल सपोर्ट',
            userIdentities: 'उपयोगकर्ता पहचान',
            vendorNodes: 'विक्रेता नोड्स',
            nexusApprovals: 'नेक्सस अनुमोदन',
            accessSecurity: 'पहुंच सुरक्षा',
            coreProtocol: 'कोर प्रोटोकॉल',
            fleetOps: 'फ्लीट ऑप्स',
            nexusMeta: 'नेक्सस मेटा',
            deactivateToken: 'टोकन निष्क्रिय करें',
            protocolStream: 'प्रोटोकॉल स्ट्रीम',
            status: 'स्थिति',
            nominal: 'नाममात्र',
            systemOverlord: 'सिस्टम ओवरलॉर्ड',
            superUser: 'सुपर यूजर',
            userManagement: 'उपयोगकर्ता प्रबंधन',
            manageUsersDesc: 'प्लेटफ़ॉर्म उपयोगकर्ताओं को प्रबंधित करें और सदस्यताएँ देखें',
            searchUsers: 'उपयोगकर्ता खोजें...',
            user: 'उपयोगकर्ता',
            role: 'भूमिका',
            subscribedAgents: 'सदस्यता प्राप्त एजेंट',
            totalSpent: 'कुल खर्च',
            actions: 'कार्य',
            admin: 'एडमिन',
            userRole: 'उपयोगकर्ता',
            active: 'सक्रिय',
            pending: 'लंबित',
            blocked: 'अवरुद्ध',
            myApps: 'मेरे ऐप',
            yourApps: 'आपके ऐप',
            newApp: 'नया ऐप',
            appName: 'ऐप का नाम',
            pricing: 'मूल्य निर्धारण',
            quickActions: 'त्वरित कार्य',
            success: 'सफलता!',
            appCreatedSuccess: 'ऐप "{name}" सफलतापूर्वक बनाया गया है और आपकी इन्वेंट्री में जोड़ दिया गया है।',
            approvals: 'अनुमोदन',
            verification: 'सत्यापन',
            identityIntegrityAudit: 'पहचान और अखंडता ऑडिट',
            pendingCases: 'लंबित मामले',
            source: 'स्रोत',
            externalVendor: 'बाहरी विक्रेता',
            authorize: 'अधिकृत करें',
            queueDepleted: 'कतार समाप्त',
            noPendingVerifications: 'कोई लंबित सत्यापन चक्र नहीं',
            finalApproval: 'अंतिम अनुमोदन',
            authorizeAgentDesc: 'क्या आप सार्वजनिक वितरण के लिए इस एजेंट को अधिकृत करना चाहते हैं? आप विक्रेता के लिए एक सिस्टम सूचना जोड़ सकते हैं।',
            regress: 'पीछे हटें',
            verifyCase: 'मामले का सत्यापन करें',
            'business os': 'बिज़नेस ओएस',
            'data & intelligence': 'डेटा और इंटेलिजेंस',
            'sales & marketing': 'सेल्स और मार्केटिंग',
            'hr & finance': 'एचआर और फाइनेंस',
            'design & creative': 'डिज़ाइन और क्रिएटिव',
            'medical & health ai': 'मेडिकल और हेल्थ एआई',
            userSupport: 'उपयोगकर्ता सहायता',
            manageInquiriesDesc: 'उपयोगकर्ता पूछताछ और सहायता टिकटों को प्रबंधित करें',
            searchTickets: 'उपयोगकर्ता या टिकट खोजें...',
            messagePreview: 'संदेश पूर्वावलोकन',
            date: 'तारीख',
            userSupportType: 'उपयोगकर्ता सहायता',
            open: 'खुला है',
            noActiveTickets: 'कोई सक्रिय टिकट नहीं',
            accessPermissionsUpdateRequired: 'पहुंच अनुमतियों के अपडेट की आवश्यकता है',
            accessPermissionsUpdateMsg: 'आपकी खाता क्षमताएं बदल गई हैं। एडमिन कंसोल तक पहुंचने के लिए कृपया अपने सुरक्षित सत्र को रिफ्रेश करें।',
            updateSession: 'सत्र अपडेट करें (लॉग आउट)',
            vendorSupport: 'विक्रेता सहायता',
            manageVendorInquiries: 'विक्रेता सहायता टिकटों और समस्याओं का प्रबंधन करें',
            all: 'सभी',
            ticketId: 'टिकट आईडी',
            description: 'विवरण',
            reply: 'जवाब दें',
            resolve: 'समाधान करें',
            noVendorTickets: 'कोई विक्रेता सहायता टिकट नहीं मिला।'
        },
        es: {
            title: 'Español (Spanish)',
            chat: 'Chat',
            myAgents: 'Mis Agentes',
            marketplace: 'Mercado',
            settings: 'Ajustes',
            adminDashboard: 'Panel de Admin',
            notifications: 'Notificaciones',
            personalProfile: 'Perfil Personal',
            helpFaq: 'Ayuda y FAQ',
            signOut: 'Cerrar Sesión',
            language: 'Idioma',
            mode: 'Modo',
            light: 'CLARO',
            dark: 'OSCURO',
            activeConnection: 'Conexión Activa',
            typeMessage: 'Escribe tu mensaje seguro...',
            privateSupport: 'Soporte Privado',
            secureProtocol: 'PROTOCOLO SEGURO ACTIVO',
            history: 'Historial',
            newInstance: 'Nueva Instancia',
            memoryEmpty: 'Memoria Vacía',
            initializeLogic: 'INICIALIZAR LÓGICA',
            chatGreeting: 'Tu agente de IA avanzado está calibrado y listo para interactuar. ¿Cómo podemos optimizar tu flujo de trabajo hoy?',
            askPlaceholder: 'Preguntar a Aisa...',
            my: 'Mis',
            agentsHeading: 'Agentes.',
            manageAgentsDesc: 'Administra tu colección de agentes de IA.',
            docs: 'Docs',
            use: 'USAR',
            info: 'Info',
            marketplaceHeading: 'AI MALL MARKETPLACE',
            marketplaceSubheading: 'DESCUBRE AGENTES INTELIGENTES',
            aiAgents: 'AGENTES DE IA',
            searchPlaceholder: 'BUSCAR AGENTES...',
            viewInfo: 'VER INFO',
            notificationsHeading: 'Notificaciones',
            notificationsDesc: 'Mantente al día con tus últimas alertas.',
            markAsRead: 'MARCAR COMO LEÍDO',
            delete: 'ELIMINAR',
            noNotificationsTitle: 'Secuencia de Vacío Nulo',
            noNotificationsDesc: 'No se detectaron transmisiones neuronales. Tu ecosistema está alcanzando su estabilidad máxima.',
            onlineReady: 'En línea y listo',
            processingReality: 'Procesando realidad',
            synced: 'SINCRONIZADO',
            untitledSession: 'Sesión sin título',
            cancel: 'CANCELAR',
            subscribeNow: 'SUSCRIBIRSE AHORA',
            chatHistory: 'HISTORIAL DEL CHAT',
            catAll: 'TODO',
            catBusiness: 'SO EMPRESARIAL',
            catData: 'DATOS E INTELIGENCIA',
            catSales: 'VENTAS Y MARKETING',
            catHr: 'RRHH Y FINANZAS',
            catDesign: 'DISEÑO Y CREATIVIDAD',
            catMedical: 'IA MÉDICA Y SALUD',
            knowledge: 'CONOCIMIENTO',
            support: 'SOPORTE',
            generalGuidelines: 'DIRECTRICES GENERALES',
            issueCategory: 'CATEGORÍA DEL PROBLEMA',
            caseDetails: 'DETALLES DEL CASO',
            specifyRequest: 'Especifique su solicitud...',
            sendMessage: 'ENVIAR MENSAJE',
            sending: 'ENVIANDO...',
            ticketCreated: '¡TICKET CREADO!',
            dismiss: 'DESCARTAR',
            directChannel: 'Canal Directo',
            generalInquiry: 'Consulta general',
            paymentIssue: 'Problema de pago',
            refundRequest: 'Solicitud de reembolso',
            technicalSupport: 'Soporte técnico',
            accountAccess: 'Acceso a la cuenta',
            other: 'Otro',
            criticalAlert: 'ALERTA CRÍTICA',
            systemMaintenance: 'MANTENIMIENTO DEL SISTEMA',
            killSwitchMsg: 'Interruptor de apagado global activado. Todos los servicios de IA están suspendidos momentáneamente.',
            maintenanceMsg: 'El sistema está actualmente en modo de mantenimiento.',
            faq1_q: "¿Qué es exactamente AI-Mall?",
            faq1_a: "Es un mercado de agentes de IA especializados. A diferencia de un chatbot genérico, eliges 'empleados' (Agentes) específicos para tareas específicas como codificación, escritura o análisis.",
            faq2_q: "¿Cómo funciona el plan de suscripción?",
            faq2_a: "Ofrecemos un modelo de suscripción flexible por agente. Puede elegir un plan que se adapte a las necesidades de su negocio, con opciones para escalar a medida que crece.",
            faq3_q: "¿Qué modelos de IA impulsan a estos agentes?",
            faq3_a: "Utilizamos modelos avanzados de IA para garantizar una alta velocidad y capacidades de razonamiento.",
            faq4_q: "¿Mis datos están seguros en el servidor?",
            faq4_a: "Sí, nuestros servidores son de grado empresarial. Utilizamos entornos aislados para cada sesión y cumplimos estrictamente con los protocolos de privacidad de datos para garantizar que su información esté segura.",
            faq5_q: "¿Cuántos agentes puedo usar ahora mismo?",
            faq5_a: "Actualmente mostramos nuestros 2 mejores agentes, AIBOT y AICRAFT, que cubren la gama más amplia de casos de uso empresarial.",
            faq6_q: "¿Puedo crear mi propio agente?",
            faq6_a: "Actualmente, el mercado cuenta con nuestros agentes seleccionados y verificados. La creación de agentes personalizados está en nuestra hoja de ruta para la próxima fase.",
            faq7_q: "¿Por qué debería usar esto sobre otras soluciones de IA?",
            faq7_a: "AI-Mall ofrece una experiencia curada con flujos especializados. No necesitas ingeniería de prompt; nuestros agentes ya están ajustados para sus trabajos específicos.",
            faq8_q: "¿Es apto para móviles?",
            faq8_a: "Sí, la interfaz es totalmente receptiva y funciona sin problemas en tu teléfono o tableta.",
            faq9_q: "¿Cómo empiezo?",
            faq9_a: "Puede probar la demostración ahora mismo o reservar un recorrido personalizado con nuestro equipo para ver cómo se adapta a su flujo de trabajo específico.",
            syncingData: 'Sincronizando datos de Nexus...',
            secDataPrivacy: "Privacidad y Protección de Datos",
            secAcceptableConduct: "Conducta Neural Aceptable",
            secDisclaimer: "Descargo de Responsabilidad de IA",
            secHeading: "Seguridad y Directrices.",
            secSubheading: "Estableciendo el marco para el uso legal, protección de datos y seguridad operativa dentro de la biosfera de AI-Mall™.",
            secSupportNode: "Nodo de Soporte",
            secSupportDesc: "¿Encuentra anomalías o necesita intervención manual? Nuestra matriz de soporte está lista.",
            secIncidentReport: "Informe de Incidentes",
            secIncidentDesc: "Informe artefactos, errores lógicos o brechas a nuestro equipo de ingeniería.",
            secOpenDiagnosis: "Abrir Formulario de Diagnóstico",
            secDataCollection: "1.1 Recolección de Datos",
            secDataSharing: "1.2 Intercambio de Datos",
            servicesRestored: 'SERVICIOS RESTAURADOS',
            subExpiringSoon: 'Suscripción por Expirar',
            newSupportReply: 'Nueva Respuesta de Soporte',
            killSwitchDeactivatedMsg: 'Interruptor de apagado global desactivado. Todos los servicios de IA están ahora activos.',
            subExpiringMsg: "Recordatorio: Su suscripción para '{agentName}' vence en menos de 2 días.",
            supportReplyMsg: "Se ha añadido una nueva respuesta a su ticket: {subject}",
            systemRestored: 'SISTEMA RESTAURADO',
            maintenanceCompleteMsg: 'El mantenimiento ha finalizado. El sistema está totalmente operativo.',
            moreIn: 'MÁS EN {category}',
            noOtherApps: 'Aún no hay otras aplicaciones en esta categoría.',
            'fireflies.ai': 'fireflies.ai',
            'AI meeting assistant that automatically records, transcribes, and summarizes conversations from calls and meetings, making collaboration and note-taking effortless for teams.': 'Asistente de reuniones de IA que graba, transcribe y resume automáticamente las conversaciones de llamadas y reuniones, facilitando la colaboración y la toma de notas para los equipos.',
            'ElevenLabs': 'ElevenLabs',
            'ElevenLabs provides creators, developers, and enterprises with state-of-the-art AI audio technology for generating and customizing speech and sound across various applications.': 'ElevenLabs proporciona a creadores, desarrolladores y empresas tecnología de audio de IA de vanguardia para generar y personalizar voz y sonido en diversas aplicaciones.',
            'AIBOT': 'AIBOT',
            'AICRAFT': 'AICRAFT'
        },
        fr: {
            title: 'Français (French)',
            chat: 'Chat',
            myAgents: 'Mes Agents',
            marketplace: 'Boutique',
            settings: 'Paramètres',
            adminDashboard: 'Tableau de bord',
            notifications: 'Notifications',
            personalProfile: 'Profil Personnel',
            helpFaq: 'Aide & FAQ',
            signOut: 'Déconnexion',
            language: 'Langue',
            mode: 'Mode',
            light: 'CLAIR',
            dark: 'SOMBRE',
            activeConnection: 'Connexion Active',
            typeMessage: 'Tapez votre message...',
            use: 'UTILISER',
            info: 'Info',
            cancel: 'ANNULER',
            subscribeNow: 'S\'ABONNER',
            knowledge: 'CONNAISSANCES',
            support: 'SUPPORT',
            dismiss: 'REJETER',
            personalProfile: 'Profil Personnel',
            notifications: 'Notifications',
            signOut: 'Déconnexion',
            settings: 'Paramètres',
            adminDashboard: 'Tableau de bord',
            mode: 'Mode',
            light: 'CLAIR',
            dark: 'SOMBRE'
        },
        de: {
            title: 'Deutsch (German)',
            chat: 'Chat',
            myAgents: 'Meine Agenten',
            marketplace: 'Marktplatz',
            settings: 'Einstellungen',
            adminDashboard: 'Admin-Dashboard',
            notifications: 'Benachrichtigungen',
            personalProfile: 'Persönliches Profil',
            helpFaq: 'Hilfe & FAQ',
            signOut: 'Abmelden',
            language: 'Sprache',
            mode: 'Modus',
            light: 'HELL',
            dark: 'DUNKEL',
            activeConnection: 'Aktive Verbindung',
            typeMessage: 'Nachricht eingeben...',
            use: 'NUTZEN',
            info: 'Info',
            cancel: 'ABBRECHEN',
            subscribeNow: 'JETZT ABONNIEREN',
            knowledge: 'WISSEN',
            support: 'UNTERSTÜTZUNG',
            dismiss: 'VERWERFEN',
            personalProfile: 'Persönliches Profil',
            notifications: 'Benachrichtigungen',
            signOut: 'Abmelden',
            settings: 'Einstellungen',
            adminDashboard: 'Admin-Dashboard',
            mode: 'Modus',
            light: 'HELL',
            dark: 'DUNKEL'
        },
        ru: {
            title: 'Русский (Russian)',
            chat: 'Чат',
            myAgents: 'Мои агенты',
            marketplace: 'Магазин',
            settings: 'Настройки',
            adminDashboard: 'Админ-панель',
            notifications: 'Уведомления',
            personalProfile: 'Личный профиль',
            helpFaq: 'Помощь и FAQ',
            signOut: 'Выйти',
            language: 'Язык',
            mode: 'Режим',
            light: 'СВЕТЛЫЙ',
            dark: 'ТЕМНЫЙ',
            activeConnection: 'Активное соединение',
            typeMessage: 'Введите сообщение...',
            use: 'ИСПОЛЬЗОВАТЬ',
            info: 'Инфо',
            cancel: 'ОТМЕНА',
            subscribeNow: 'ПОДПИСАТЬСЯ',
            knowledge: 'ЗНАНИЯ',
            support: 'ПОДДЕРЖКА',
            dismiss: 'ОТКЛОНИТЬ',
            personalProfile: 'Личный профиль',
            notifications: 'Уведомления',
            signOut: 'Выйти',
            settings: 'Настройки',
            adminDashboard: 'Админ-панель',
            mode: 'Режим',
            light: 'СВЕТЛЫЙ',
            dark: 'ТЕМНЫЙ'
        },
        zh: {
            title: '中文 (Chinese)',
            chat: '聊天',
            myAgents: '我的代理',
            marketplace: '市场',
            settings: '设置',
            adminDashboard: '管理面板',
            notifications: '通知',
            personalProfile: '个人资料',
            helpFaq: '帮助与常见问题',
            signOut: '登出',
            language: '语言',
            mode: '模式',
            light: '浅色',
            dark: '深色',
            activeConnection: '当前连接',
            typeMessage: '在此输入加密消息...',
            use: '使用',
            info: '详情',
            cancel: '取消',
            subscribeNow: '立即订阅',
            knowledge: '知识库',
            support: '支持',
            dismiss: '关闭',
            personalProfile: '个人资料',
            notifications: '通知',
            signOut: '登出',
            settings: '设置',
            adminDashboard: '管理面板',
            mode: '模式',
            light: '浅色',
            dark: '深色'
        },
        ja: {
            title: '日本語 (Japanese)',
            chat: 'チャット',
            myAgents: 'マイエージェント',
            marketplace: 'マーケット',
            settings: '設定',
            adminDashboard: '管理画面',
            notifications: '通知',
            personalProfile: 'プロフィール',
            helpFaq: 'ヘルプとFAQ',
            signOut: 'ログアウト',
            language: '言語',
            mode: 'モード',
            light: 'ライト',
            dark: 'ダーク',
            activeConnection: 'アクティブ接続',
            typeMessage: 'メッセージを入力...',
            use: '使う',
            info: '情報',
            cancel: 'キャンセル',
            subscribeNow: '購読する',
            knowledge: 'ナレッジ',
            support: 'サポート',
            dismiss: '閉じる',
            personalProfile: 'プロフィール',
            notifications: '通知',
            signOut: 'ログアウト',
            settings: '設定',
            adminDashboard: '管理画面',
            mode: 'モード',
            light: 'ライト',
            dark: 'ダーク'
        },
        pt: {
            title: 'Português (Portuguese)',
            chat: 'Chat',
            myAgents: 'Meus Agentes',
            marketplace: 'Mercado',
            settings: 'Configurações',
            adminDashboard: 'Painel Admin',
            notifications: 'Notificações',
            personalProfile: 'Perfil Pessoal',
            helpFaq: 'Ajuda & FAQ',
            signOut: 'Sair',
            language: 'Idioma',
            mode: 'Modo',
            light: 'CLARO',
            dark: 'ESCURO',
            activeConnection: 'Conexão Ativa',
            typeMessage: 'Digite sua mensagem...',
            use: 'USAR',
            info: 'Info',
            cancel: 'CANCELAR',
            subscribeNow: 'ASSINAR AGORA',
            knowledge: 'CONHECIMENTO',
            support: 'SUPORTE',
            dismiss: 'DESCARTAR',
            personalProfile: 'Perfil Pessoal',
            notifications: 'Notificações',
            signOut: 'Sair',
            settings: 'Configurações',
            adminDashboard: 'Painel Admin',
            mode: 'Modo',
            light: 'CLARO',
            dark: 'ESCURO'
        },
        sa: {
            title: 'संस्कृतम् (Sanskrit)',
            chat: 'संभाषणम्',
            myAgents: 'मदीयाः एजेण्ट्स्',
            marketplace: 'कविपण्यम्',
            settings: 'समायोजनानि',
            adminDashboard: 'प्रशासक फलकम्',
            notifications: 'सूचनाः',
            personalProfile: 'वैयक्तिक वृत्तम्',
            helpFaq: 'सहायता च प्रश्नावलिः',
            signOut: 'निर्गमनम्',
            language: 'भाषा',
            mode: 'विधिः',
            light: 'प्रकाशः',
            dark: 'अन्धकारः',
            use: 'उपयोगः',
            info: 'सूचना',
            knowledge: 'ज्ञानम्',
            support: 'सहायता',
            dismiss: 'निरसनम्'
        },
        mr: {
            title: 'मराठी (Marathi)',
            chat: 'चॅट',
            myAgents: 'माझे एजंट्स',
            marketplace: 'मार्केटप्लेस',
            settings: 'सेटिंग्ज',
            adminDashboard: 'अ‍ॅडमिन डॅशबोर्ड',
            notifications: 'सूचना',
            personalProfile: 'वैयक्तिक प्रोफाइल',
            helpFaq: 'मदत आणि विचारले जाणारे प्रश्न',
            signOut: 'साइन आउट',
            language: 'भाषा',
            mode: 'मोड',
            light: 'लाईट',
            dark: 'डार्क',
            use: 'वापरा',
            info: 'माहिती',
            knowledge: 'ज्ञान',
            support: 'मदत',
            dismiss: 'रद्द करा'
        },
        bn: {
            title: 'বাংলা (Bengali)',
            chat: 'চ্যাট',
            myAgents: 'আমার এজেন্টরা',
            marketplace: 'মার্কেটপ্লেস',
            settings: 'সেটিংস',
            adminDashboard: 'অ্যাডমিন ড্যাশবোর্ড',
            notifications: 'বিজ্ঞপ্তি',
            personalProfile: 'ব্যক্তিগত প্রোফাইল',
            helpFaq: 'সাহায্য এবং প্রশ্নাবলী',
            signOut: 'সাইন আউট',
            language: 'ভাষা',
            mode: 'মোড',
            light: 'লাইট',
            dark: 'ডার্ক',
            use: 'ব্যবহার করুন',
            info: 'তথ্য',
            knowledge: 'জ্ঞান',
            support: 'সহায়তা',
            dismiss: 'খারিজ করুন'
        },
        ta: {
            title: 'தமிழ் (Tamil)',
            chat: 'அரட்டை',
            myAgents: 'எனது முகவர்கள்',
            marketplace: 'சந்தை',
            settings: 'அமைப்புகள்',
            adminDashboard: 'நிர்வாகப் பலகம்',
            notifications: 'அறிவிப்புகள்',
            personalProfile: 'தனிப்பட்ட விவரம்',
            helpFaq: 'உதவி மற்றும் கேள்விகள்',
            signOut: 'வெளியேறு',
            language: 'மொழி',
            mode: 'முறை',
            light: 'ஒளி',
            dark: 'இருள்',
            use: 'பயன்படுத்து',
            info: 'தகவல்',
            knowledge: 'அறிவு',
            support: 'ஆதரவு',
            dismiss: 'நீக்கு'
        },
        pa: {
            title: 'ਪੰਜਾਬੀ (Punjabi)',
            chat: 'ਚੈਟ',
            myAgents: 'ਮੇਰੇ ਏਜੰਟ',
            marketplace: 'ਮਾਰਕੀਟਪਲੇਸ',
            settings: 'ਸੈਟਿੰਗਾਂ',
            adminDashboard: 'ਐਡਮਿਨ ਡੈਸ਼ਬੋਰਡ',
            notifications: 'ਨੋਟੀਫਿਕੇਸ਼ਨ',
            personalProfile: 'ਨਿੱਜੀ ਪ੍ਰੋਫਾਈਲ',
            helpFaq: 'ਮਦਦ ਅਤੇ FAQ',
            signOut: 'ਸਾਈਨ ਆਊਟ',
            language: 'ਭਾਸ਼ਾ',
            mode: 'ਮੋਡ',
            light: 'ਲਾਈਟ',
            dark: 'ਡਾਰਕ',
            use: 'ਵਰਤੋਂ',
            info: 'ਜਾਣਕਾਰੀ',
            knowledge: 'ਗਿਆਨ',
            support: 'ਸਹਾਇਤਾ',
            dismiss: 'ਖਾਰਜ ਕਰੋ'
        },
        gu: {
            title: 'ગુજરાતી (Gujarati)',
            chat: 'ચેટ',
            myAgents: 'મારા એજન્ટ્સ',
            marketplace: 'માર્કેટપ્લેસ',
            settings: 'સેટિંગ્સ',
            adminDashboard: 'એડમિન ડેશબોર્ડ',
            notifications: 'નોટિફિકેશન',
            personalProfile: 'પર્સનલ પ્રોફાઇલ',
            helpFaq: 'મદદ અને FAQ',
            signOut: 'સાઇન આઉટ',
            language: 'ભાષા',
            mode: 'મોડ',
            light: 'લાઇટ',
            dark: 'ડાર્ક',
            use: 'વાપરો',
            info: 'માહિતી',
            knowledge: 'જ્ઞાન',
            support: 'સહાય',
            dismiss: 'રદ કરો'
        },
        kn: {
            title: 'ಕನ್ನಡ (Kannada)',
            chat: 'ಚಾಟ್',
            myAgents: 'ನನ್ನ ಏಜೆಂಟ್ಸ್',
            marketplace: 'ಮಾರ್ಕೆಟ್‌ಪ್ಲೇಸ್',
            settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
            adminDashboard: 'ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
            notifications: 'ನೋಟಿಫಿಕೇಶನ್',
            personalProfile: 'ವೈಯಕ್ತಿಕ ಪ್ರೊಫೈಲ್',
            helpFaq: 'ಸಹಾಯ ಮತ್ತು FAQ',
            signOut: 'ಸೈನ್ ಔಟ್',
            language: 'ಭಾಷೆ',
            mode: 'ಮೋಡ್',
            light: 'ಲೈಟ್',
            dark: 'ಡಾರ್ಕ್',
            use: 'ಬಳಸಿ',
            info: 'ಮಾಹಿತಿ',
            knowledge: 'ಜ್ಞಾನ',
            support: 'ಬೆಂಬಲ',
            dismiss: 'ರದ್ದುಗೊಳಿಸು'
        },
        te: {
            title: 'తెలుగు (Telugu)',
            chat: 'చాట్',
            myAgents: 'నా ఏజెంట్లు',
            marketplace: 'మార్కెట్‌ప్లేస్',
            settings: 'సెట్టింగ్‌లు',
            adminDashboard: 'అడ్మిన్ డాష్‌బోర్డ్',
            notifications: 'నోటిఫికేషన్‌లు',
            personalProfile: 'వ్యక్తిగత ప్రొఫైల్',
            helpFaq: 'ಸహాయం మరియు FAQ',
            signOut: 'సైన్ అవుట్',
            language: 'భాష',
            mode: 'మోడ్',
            light: 'లైట్',
            dark: 'డార్క్',
            use: 'ఉపయోగించండి',
            info: 'సమాచారం',
            knowledge: 'జ్ఞానం',
            support: 'మద్దతు',
            dismiss: 'రద్దు చేయి'
        },
        ml: {
            title: 'മലയാളം (Malayalam)',
            chat: 'ചാറ്റ്',
            myAgents: 'എന്റെ ഏജന്റുകൾ',
            marketplace: 'മാർക്കറ്റ് പ്ലേസ്',
            settings: 'ക്രമീകരണങ്ങൾ',
            adminDashboard: 'അഡ്മിൻ ഡാഷ്ബോർഡ്',
            notifications: 'അറിയിപ്പുകൾ',
            personalProfile: 'വ്യക്തിഗത വിവരങ്ങൾ',
            helpFaq: 'സഹായവും FAQ-വും',
            signOut: 'പുറത്തുകടക്കുക',
            language: 'ഭാഷ',
            mode: 'മോഡ്',
            light: 'ലൈറ്റ്',
            dark: 'ഡാർക്ക്',
            use: 'ഉപയോഗിക്കുക',
            info: 'വിവരം',
            knowledge: 'അറിവ്',
            support: 'പിന്തുണ',
            dismiss: 'ഒഴിവാക്കുക'
        }
    };

    const handleSetLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('preferredLanguage', lang);
    };

    const t = (key) => {
        return translations[language]?.[key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ t, language, setLanguage: handleSetLanguage, languages: translations }
        }>
            {children}
        </LanguageContext.Provider >
    );
};

export const useLanguage = () => useContext(LanguageContext);
